openapi: 3.0.3
info:
  title: STD23065 - TD3
  description: API for managing meals
  version: 1.0.2
paths:
  /meals:
    get:
      summary: Get a list of meals
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    post:
      summary: Create a new meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateMeal'
      responses:
        '201':
          description: Meal created successfully
  /meals/{mealId}:
    put:
      summary: Update an existing meal
      parameters:
        - name: mealId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMeal'
      responses:
        '200':
          description: Meal updated successfully
    delete:
      summary: Delete a meal
      parameters:
        - name: mealId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Meal deleted successfully

components:
  schemas:
    Meal:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: float
    CreateMeal:
      allOf:
        - $ref: '#/components/schemas/Meal'
        - type: object
          required:
            - name
            - price
          properties:
            id:
              type: string
              readOnly: true
    UpdateMeal:
      allOf:
        - $ref: '#/components/schemas/CreateMeal'
